site_name: GraphRAG
site_url: https://datastax.github.io/graph-rag
repo_url: https://github.com/datastax/graph-rag
edit_uri: edit/main/docs/
site_description:
extra_css:
  - styles.css
extra:
  analytics:
    provider: google
    property: "G-7DS0D7NZML"

plugins:
# Default social cards (see below to override)
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
- social
- search
- blog
- mkdocs-jupyter:
    include_source: True
    remove_tag_config:
      remove_input_tags: ["hide_code"]
      remove_cell_tags: ["hide_cell"]
      remove_all_outputs_tags: ["hide_output"]
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        inventories:
          - https://python.langchain.com/api_reference/objects.inv
          - https://networkx.org/documentation/stable/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://docs.python.org/3/objects.inv

        options:
          docstring_section_style: spacy
          docstring_style: numpy
          merge_init_into_class: true
          show_symbol_type_toc: true
          show_root_toc_entry: false
          separate_signature: true
          show_signature_annotations: true
          signature_crossrefs: true
          group_by_category: true
          inherited_members: true
          extensions:
          - griffe_inherited_docstrings
          - griffe_pydantic:
              schema: true
          filters: ["!^_[^_]"]
        paths:
        - packages/graph-retriever/src/
        - packages/langchain-graph-retriever/src/
        - packages/graph-rag-example-helpers/src/

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - def_list
  - toc:
      title: On this page
      permalink: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.tabs.link

nav:
    - Home: index.md
    - Guide:
        - guide/index.md
        - guide/get-started.md
        - guide/traversal.md
        - guide/edges.md
        - guide/strategies.md
        - guide/adapters.md
        - guide/transformers.md
    - Examples:
        - examples/index.md
        - examples/lazy-graph-rag.ipynb
    - Reference:
        - reference/index.md
        - graph-retriever:
            - reference/graph_retriever/index.md
            - reference/graph_retriever/edges.md
            - reference/graph_retriever/strategies.md
            - reference/graph_retriever/adapters.md
            - reference/graph_retriever/testing.md
            - reference/graph_retriever/utils.md
        - langchain-graph-retriever:
            - reference/langchain_graph_retriever/index.md
            - reference/langchain_graph_retriever/adapters.md
            - reference/langchain_graph_retriever/transformers.md
        - graph-rag-example-helpers:
            - reference/graph_rag_example_helpers/index.md
    - Blog:
        - blog/index.md