[project]
name = "graph-rag-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "gliner>=0.2.16",
    "keybert>=0.8.5",
    "langchain-community>=0.3.15",
    "pytest>=8.3.4",
]
