[project]
name = "graph-pancake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.deptry.package_module_name_map]
beautifulsoup4 = "bs4"
opensearch-py = "opensearchpy"

[tool.deptry.per_rule_ignores]
DEP002 = ["cassio"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["."]
testpaths = ["tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "T201"]
[tool.ruff.format]
docstring-code-format = true

[tool.uv.sources]

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=4.0.0",
    "pytest-asyncio>=0.25.2",
]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = [
    "packages/graph-rag/src/graph_rag",
    "packages/langchain-graph-rag/src/langchain_graph_rag",
    ]
