[project]
name = "graph-retriever-workspace"
version = "0.1.0"
description = "uv workspace for Graph RAG projects"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

classifiers = ["Private :: Do Not Upload"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["."]
testpaths = ["tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "T201", "D", "W"]
ignore = ["D100", "D104", "D107"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"**/{tests,docs,tools,scripts}/*" = ["D"]

[tool.ruff.format]
docstring-code-format = true

[tool.uv.sources]
graph-retriever = { workspace = true }
langchain-graph-retriever = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=4.0.0",
    "pytest-asyncio>=0.25.2",
]

docs = [
    "quartodoc>=0.9.1",
    "nbformat>=5.10.4",
    "nbclient>=0.10.2",
    "langchain-openai>=0.3.1",
    "ipykernel>=6.29.5",
    "langchain-astradb>=0.5.2",
    "langchain-graph-retriever>=0.1.0",
    "matplotlib>=3.10.0",
    "jupyterlab>=4.3.4",
    "langchain-community>=0.3.14",
    "sentence-transformers>=3.3.1",
    "langchain-huggingface>=0.1.2",
]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = [
    "packages/graph-retriever/src/graph_retriever",
    "packages/langchain-graph-retriever/src/langchain_graph_retriever",
    ]
