[project]
name = "metadata-extractors"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "gliner>=0.2.13",
    "keybert>=0.8.5",
    "pandas>=2.2.3",
]
