project:
  type: website

metadata-files:
  - reference/langchain_graph_retriever/_sidebar.yml
  - reference/graph_retriever/_sidebar.yml
  - reference/graph_rag_example_helpers/_sidebar.yml


website:
  title: Graph RAG
  twitter-card: true
  google-analytics: "G-7DS0D7NZML"
  navbar:
    background: primary
    search: true
    left:
      - guide/index.qmd
      - examples/index.qmd
      - posts/index.qmd
      - reference/index.qmd
    right:
      - icon: github
        href: https://github.com/datastax/graph-rag
      - icon: rss
        href: index.xml
  page-footer:
    border: true
    left: "© Copyright 2025, Graph RAG Contributors."
  repo-url: https://github.com/datastax/graph-rag/
  repo-subdir: docs
  repo-actions:
    - edit
    - source
  site-url: https://datastax.github.io/graph-rag
format:
  html:
    theme: pulse
    toc: true
    anchor-sections: true
    css:
      - css/_styles-quartodoc.css

    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/datastax.github.io\/graph-rag'


filters:
  - interlinks

interlinks:
  sources:
    langchain:
      url: https://python.langchain.com/api_reference/
    networkx:
      url: https://networkx.org/documentation/stable/
    numpy:
      url: https://numpy.org/doc/stable/
    python:
      url: https://docs.python.org/3/
