# API Reference {.doc .doc-index}

## graph_retriever

| | |
| --- | --- |
| [traverse](traverse.qmd#graph_retriever.traverse) | Perform a graph traversal to retrieve nodes for a specific query. |
| [atraverse](atraverse.qmd#graph_retriever.atraverse) | Perform a graph traversal to retrieve nodes for a specific query. |
| [Adapter](Adapter.qmd#graph_retriever.Adapter) | Base adapter for integrating vector stores with the graph retriever system. |
| [Content](Content.qmd#graph_retriever.Content) | Model representing retrieved content. |
| [Edge](Edge.qmd#graph_retriever.Edge) | An edge identifies properties necessary for finding matching nodes. |
| [Edges](Edges.qmd#graph_retriever.Edges) | Information about the incoming and outgoing edges. |
| [EdgeSpec](EdgeSpec.qmd#graph_retriever.EdgeSpec) |  |
| [EdgeFunction](EdgeFunction.qmd#graph_retriever.EdgeFunction) | A function for extracting edges from nodes. |
| [Id](Id.qmd#graph_retriever.Id) | Place-holder type indicating that the ID should be used. |
| [IdEdge](IdEdge.qmd#graph_retriever.IdEdge) | Nodes with `node.id == id`. |
| [MetadataEdge](MetadataEdge.qmd#graph_retriever.MetadataEdge) | Link to nodes with specific metadata. |
| [Node](Node.qmd#graph_retriever.Node) | Represents a node in the traversal graph. |

### edges

| | |
| --- | --- |
| [MetadataEdgeFunction](MetadataEdgeFunction.qmd#graph_retriever.edges.metadata.MetadataEdgeFunction) | Helper for extracting and encoding edges in metadata. |

### strategies

| | |
| --- | --- |
| [Eager](Eager.qmd#graph_retriever.strategies.eager.Eager) | Eager traversal strategy (breadth-first). |
| [Mmr](Mmr.qmd#graph_retriever.strategies.mmr.Mmr) | Maximal Marginal Relevance (MMR) traversal strategy. |
| [Strategy](Strategy.qmd#graph_retriever.strategies.Strategy) | Interface for configuring node selection and traversal strategies. |

## langchain_graph_retriever

| | |
| --- | --- |
| [GraphRetriever](GraphRetriever.qmd#langchain_graph_retriever.GraphRetriever) | Retriever combining vector search and graph traversal. |
| [document_graph](document_graph.qmd#langchain_graph_retriever.document_graph) | Utilities for creating and analyzing a graph of documents. |

### document_transformers

| | |
| --- | --- |
| [GLiNEREntityExtractor](GLiNEREntityExtractor.qmd#langchain_graph_retriever.document_transformers.gliner.GLiNEREntityExtractor) | Add metadata to documents about named entities using `GLiNER`_. |
| [HierarchyLinkExtractor](HierarchyLinkExtractor.qmd#langchain_graph_retriever.document_transformers.hierarchy.HierarchyLinkExtractor) | Extract links from a document hierarchy. |
| [HtmlHyperlinkExtractor](HtmlHyperlinkExtractor.qmd#langchain_graph_retriever.document_transformers.html_hyperlink.HtmlHyperlinkExtractor) | Extract hyperlinks from HTML content. |
| [KeybertKeywordExtractor](KeybertKeywordExtractor.qmd#langchain_graph_retriever.document_transformers.keybert.KeybertKeywordExtractor) | Add metadata to documents about keywords using `KeyBERT <https://maartengr.github.io/KeyBERT/>`_. |
| [MetadataDenormalizer](MetadataDenormalizer.qmd#langchain_graph_retriever.document_transformers.metadata_denormalizer.MetadataDenormalizer) | Denormalizes sequence-based metadata fields. |
| [SpacyNERTransformer](SpacyNERTransformer.qmd#langchain_graph_retriever.document_transformers.spacy.SpacyNERTransformer) | Add metadata to documents about named entities using `spaCy`. |

### adapters

| | |
| --- | --- |
| [LangchainAdapter](LangchainAdapter.qmd#langchain_graph_retriever.adapters.langchain.LangchainAdapter) | Base adapter for integrating vector stores with the graph retriever system. |
| [DenormalizedAdapter](DenormalizedAdapter.qmd#langchain_graph_retriever.adapters.langchain.DenormalizedAdapter) | Base adapter for integrating vector stores with the graph retriever system. |
| [AstraAdapter](AstraAdapter.qmd#langchain_graph_retriever.adapters.astra.AstraAdapter) | Adapter for AstraDBVectorStore. |
| [CassandraAdapter](CassandraAdapter.qmd#langchain_graph_retriever.adapters.cassandra.CassandraAdapter) | Adapter for Cassandra vector store. |
| [ChromaAdapter](ChromaAdapter.qmd#langchain_graph_retriever.adapters.chroma.ChromaAdapter) | Adapter for Chroma vector store. |
| [InMemoryAdapter](InMemoryAdapter.qmd#langchain_graph_retriever.adapters.in_memory.InMemoryAdapter) | Adapter for InMemoryVectorStore vector store. |
| [OpenSearchAdapter](OpenSearchAdapter.qmd#langchain_graph_retriever.adapters.open_search.OpenSearchAdapter) | Adapter to traverse OpenSearch vector stores. |
| [inference](inference.qmd#langchain_graph_retriever.adapters.inference) | Infers the appropriate adapter for a given vector store. |

## graph_rag_example_helpers